# Generated by Django 2.0.6 on 2020-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_diagnostico', models.CharField(max_length=200)),
                ('descripcion_diagnostico', models.CharField(max_length=200)),
            ],
        ),
    ]
