# Generated by Django 2.0.6 on 2020-12-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='experto',
            fields=[
                ('id_experto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'experto',
                'verbose_name_plural': 'expertos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'ordering': ['nombre_diagnostico'], 'verbose_name': 'diagnostico', 'verbose_name_plural': 'diagnosticos'},
        ),
    ]
