# Generated by Django 2.0.6 on 2020-12-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_auto_20201206_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experto',
            name='especialidad',
        ),
    ]
