# Generated by Django 2.0.6 on 2020-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0003_remove_experto_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
                'ordering': ['nombre_especialidad'],
            },
        ),
    ]
