# Generated by Django 2.0.6 on 2020-12-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0004_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='experto',
            name='id_especialidad',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='diagnostico.especialidad'),
        ),
    ]
